<?php
return array (
  14 => 
  array (
    'id' => '14',
    'catid' => '22',
    'typeid' => '0',
    'title' => '项目运营',
    'style' => '',
    'thumb' => 'http://liangyou.com/uploadfile/2015/0604/20150604111628453.jpg',
    'keywords' => '项目',
    'description' => '项目运营',
    'posids' => '0',
    'url' => 'http://liangyou.com/index.php?m=content&c=index&a=show&catid=22&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433430964',
    'updatetime' => '1433430992',
    'hitsid' => 'c-1-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '22',
    'typeid' => '0',
    'title' => '渠道发行',
    'style' => '',
    'thumb' => 'http://liangyou.com/uploadfile/2015/0604/20150604111658704.jpg',
    'keywords' => '渠道',
    'description' => '渠道发行',
    'posids' => '0',
    'url' => 'http://liangyou.com/index.php?m=content&c=index&a=show&catid=22&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433430996',
    'updatetime' => '1433431022',
    'hitsid' => 'c-1-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '22',
    'typeid' => '0',
    'title' => '广告资源',
    'style' => '',
    'thumb' => 'http://liangyou.com/uploadfile/2015/0604/20150604111807824.jpg',
    'keywords' => '广告 资源',
    'description' => '广告资源广告资源广告资源广告资源',
    'posids' => '0',
    'url' => 'http://liangyou.com/index.php?m=content&c=index&a=show&catid=22&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433431067',
    'updatetime' => '1433431090',
    'hitsid' => 'c-1-16',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '22',
    'typeid' => '0',
    'title' => '合作制片',
    'style' => '',
    'thumb' => 'http://liangyou.com/uploadfile/2015/0604/20150604111837915.jpg',
    'keywords' => '合作制片',
    'description' => '合作制片合作制片合作制片合作制片合作制片合作制片合作制片合作制片合作制片',
    'posids' => '0',
    'url' => 'http://liangyou.com/index.php?m=content&c=index&a=show&catid=22&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433431094',
    'updatetime' => '1433431120',
    'hitsid' => 'c-1-17',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '22',
    'typeid' => '0',
    'title' => '新媒体运营',
    'style' => '',
    'thumb' => 'http://liangyou.com/uploadfile/2015/0604/20150604112904801.jpg',
    'keywords' => '媒体',
    'description' => '新媒体运营新媒体运营新媒体运营新媒体运营新媒体运营',
    'posids' => '0',
    'url' => 'http://liangyou.com/index.php?m=content&c=index&a=show&catid=22&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433431718',
    'updatetime' => '1433433053',
    'hitsid' => 'c-1-18',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>