<?php
return array (
  8 => 
  array (
    'id' => '8',
    'catid' => '31',
    'typeid' => '0',
    'title' => '网上选片测试1',
    'style' => '',
    'thumb' => 'http://liangyou.com/uploadfile/2015/0607/20150607022549135.jpg',
    'keywords' => '网上选片测试1',
    'description' => '网上选片测试1网上选片测试1网上选片测试1网上选片测试1网上选片测试1网上选片测试1网上选片测试1网上选片测试1网上选片测试1网上选片测试1网上选片测试1网上选片测试1网上选片测试1网上',
    'posids' => '0',
    'url' => 'http://liangyou.com/index.php?m=content&c=index&a=show&catid=31&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433615532',
    'updatetime' => '1433615603',
    'en_title' => 'xuanpian',
    'director' => '陈建设',
    'area' => '北京',
    'produced' => '良友(北京)文化传媒有限公司',
    'duration' => '4集 45分钟',
    'stills' => '',
    'link_url' => 'http://www.baidu.com',
    'hitsid' => 'c-12-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '31',
    'typeid' => '0',
    'title' => '网上选片测试2',
    'style' => '',
    'thumb' => 'http://liangyou.com/uploadfile/2015/0607/20150607022523115.jpg',
    'keywords' => '网上选片测试2',
    'description' => '网上选片测试2网上选片测试2网上选片测试2网上选片测试2网上选片测试2网上选片测试2',
    'posids' => '0',
    'url' => 'http://liangyou.com/index.php?m=content&c=index&a=show&catid=31&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433615608',
    'updatetime' => '1433615664',
    'en_title' => 'xuanpian2',
    'director' => '陈鑫',
    'area' => '北京',
    'produced' => '良友(北京)文化传媒有限公司',
    'duration' => '4集 45分钟',
    'stills' => '',
    'link_url' => 'http://www.baidu.com',
    'hitsid' => 'c-12-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>