<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '14',
    'typeid' => '0',
    'title' => '《2015GZDOC》',
    'style' => '',
    'thumb' => 'http://localhost/liangyou/uploadfile/2015/0531/20150531125150937.jpg',
    'keywords' => '《2015GZDOC》',
    'description' => '第五届广州纪录片节第五届广州纪第五届广州纪第五届广州纪开幕',
    'posids' => '1',
    'url' => 'http://localhost/liangyou/index.php?m=content&c=index&a=show&catid=14&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433047788',
    'updatetime' => '1433047810',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '14',
    'typeid' => '0',
    'title' => '2015GZDOC',
    'style' => '',
    'thumb' => 'http://localhost/liangyou/uploadfile/2015/0531/20150531043503355.jpg',
    'keywords' => '测试',
    'description' => '第五届广州纪录片节第五届广州纪第五届广州纪第五届广州纪开幕第五届广州纪录片节第五届广州纪第五届广州纪第五届广州纪开幕',
    'posids' => '0',
    'url' => 'http://localhost/liangyou/index.php?m=content&c=index&a=show&catid=14&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433061287',
    'updatetime' => '1433061306',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>