<?php
return array (
  4 => 
  array (
    'id' => '4',
    'catid' => '29',
    'typeid' => '0',
    'title' => '豆腐味道',
    'style' => '',
    'thumb' => 'http://liangyou.com/uploadfile/2015/0607/20150607022618338.jpg',
    'keywords' => '豆腐 味道',
    'description' => '豆腐味道豆腐味道豆腐味道豆腐味道豆腐味道豆腐味道豆腐味道豆腐味道豆腐味道豆腐味道豆腐味道豆腐味道豆腐味道',
    'posids' => '0',
    'url' => 'http://liangyou.com/index.php?m=content&c=index&a=show&catid=29&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433615055',
    'updatetime' => '1433615182',
    'en_title' => 'doufu',
    'director' => '陈建设',
    'area' => '中国大陆',
    'produced' => '良友(北京)文化传媒有限公司',
    'duration' => '4集 45分钟',
    'stills' => '',
    'link_url' => 'http://www.baidu.com',
    'hitsid' => 'c-12-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '29',
    'typeid' => '0',
    'title' => '豆腐味道2',
    'style' => '',
    'thumb' => 'http://liangyou.com/uploadfile/2015/0607/20150607022557993.jpg',
    'keywords' => '豆腐 味道',
    'description' => '豆腐味道2豆腐味道2豆腐味道2豆腐味道2豆腐味道2豆腐味道2豆腐味道2豆腐味道2豆腐味道2豆腐味道2豆腐味道2豆腐味道2豆腐味道2',
    'posids' => '0',
    'url' => 'http://liangyou.com/index.php?m=content&c=index&a=show&catid=29&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'sunzheng',
    'inputtime' => '1433615196',
    'updatetime' => '1433615317',
    'en_title' => 'doufu2',
    'director' => '陈建设',
    'area' => '中国大陆',
    'produced' => '良友(北京)文化传媒有限公司',
    'duration' => '4集 45分钟',
    'stills' => '',
    'link_url' => 'http://www.baidu.com',
    'hitsid' => 'c-12-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>